# Change these first
owner: solplparty # Your GitHub username
repo: upptime # Your Github repository name

# Add your sites here
sites:
  - name: solplparty.com
    url: https://solplparty.com
  - name: solpl.party
    url: https://solpl.party   
  - name: about.solpl.party
    url: https://about.solpl.party
  - name: culture.solpl.party
    url: https://culture.solpl.party
  - name: idoluv.me
    url: https://idoluv.me
  - name: BLUV
    url: https://bluv.solpl.party/

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.solpl.party
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** for SOLPL PARTY"
  introMessage: π¤ λ¬Έν™”μμ  μ»¤λ®¤λ‹ν‹°, μ†”ν”νν‹°κ°€ μ΄μν•λ” μ„λΉ„μ¤μ ν„μ¬ μƒνƒμ…λ‹λ‹¤. (Run by. GitHub Actions)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

notifications:
  - type: discord
    DISCORD_WEBHOOK_URL: https://discord.com/api/webhooks/773254434071379968/Crv3PzbTUs18IFGXGg4k0TJUfUtTtMAB66fbY-3QlOMQq2j5cYTvuKNJdb3AyCFmAFH2

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
