# Change these first
owner: solplparty # Your GitHub username
repo: upptime # Your Github repository name

# Add your sites here
sites:
  - name: solplparty.com
    url: https://solplparty.com
  - name: solpl.party
    url: https://solpl.party   
  - name: about.solpl.party
    url: https://about.solpl.party
  - name: culture.solpl.party
    url: https://culture.solpl.party
  - name: idoluv.me
    url: https://idoluv.me
  - name: BLUV
    url: https://bluv.solpl.party/

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.solpl.party
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** for SOLPL PARTY"
  introMessage: 🤘 문화예술 커뮤니티, 솔플파티가 운영하는 서비스의 현재 상태입니다. (Run by. GitHub Actions)

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
